# Generated by Django 4.1.6 on 2023-08-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_pdffile_prediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdffile",
            name="num_pages",
            field=models.IntegerField(default=True),
        ),
    ]
