# Generated by Django 4.1.6 on 2023-08-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_pdffile_num_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdffile",
            name="key",
            field=models.CharField(default=True, max_length=200),
        ),
    ]
